apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-k8s
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-k8s
  template:
    metadata:
      labels:
        app: hello-spring-k8s
    spec:
      containers:
      - name: hello-spring-k8s
        image: ${DOCKERHUB_USERNAME}/hello-spring-k8s:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m" 