apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloSpringK8s.name }}
  namespace: default
spec:
  selector:
    app: {{ .Values.helloSpringK8s.name }}
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 