name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  HELLO_SERVICE_IMAGE: ${{ github.repository }}-hello-service
  HELLO_CALLER_IMAGE: ${{ github.repository }}-hello-caller

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push hello-service
        uses: docker/build-push-action@v5
        with:
          context: ./hello-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.HELLO_SERVICE_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push hello-caller
        uses: docker/build-push-action@v5
        with:
          context: ./hello-caller
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.HELLO_CALLER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update README with image tags
        run: |
          echo "## Latest Docker Images" >> README.md
          echo "" >> README.md
          echo "Latest images are available at:" >> README.md
          echo "- hello-service: \`${{ env.REGISTRY }}/${{ env.HELLO_SERVICE_IMAGE }}:${{ github.sha }}\`" >> README.md
          echo "- hello-caller: \`${{ env.REGISTRY }}/${{ env.HELLO_CALLER_IMAGE }}:${{ github.sha }}\`" >> README.md
          echo "" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest image tags"
          git push 